const app = document.getElementById('app');
let mode = new URLSearchParams(location.search).get('mode') || 'creator';
let creatorTab = 'home';

const creator = { name: 'Maya', tier: 'HIGH TRUST', rating: '4.96', completed: 184 };

function topbar(extra='') { return `<div class="topbar"><div><div class="brand">Paid</div><div class="kicker">${extra}</div></div><button class="text-button" onclick="setMode('${mode === 'creator' ? 'buyer' : 'creator'}')">${mode === 'creator' ? 'Buyer demo' : 'Creator demo'}</button></div>`; }
function nav() { return `<nav class="nav" aria-label="Creator"><button class="${creatorTab==='home'?'active':''}" onclick="tab('home')">Home</button><button class="${creatorTab==='transactions'?'active':''}" onclick="tab('transactions')">Activity</button><button class="${creatorTab==='create'?'active':''}" onclick="tab('create')">Create</button><button class="${creatorTab==='trust'?'active':''}" onclick="tab('trust')">Trust</button><button class="${creatorTab==='account'?'active':''}" onclick="tab('account')">Account</button></nav>`; }
function setMode(next){ mode=next; render(); }
function tab(next){ creatorTab=next; render(); }

function creatorHome(){ return `<section class="page">${topbar('Creator home')}<div class="kicker">Available</div><div class="amount">$842.60</div><div class="meta row"><span>Pending $391.20</span><span>Next payout Tue</span></div><div class="section"><button class="primary" onclick="tab('create')">Create link</button></div><div class="section trust"><div><div class="kicker">${creator.tier}</div><h2>${creator.rating} ★</h2><div class="meta">${creator.completed} completed transactions</div></div><span class="badge">VERIFIED</span></div><div class="section"><div class="row"><h2>Recent</h2><button class="text-button" onclick="tab('transactions')">See all</button></div><div class="tx"><strong>A82F · $50</strong><span>48h</span><span class="status">Awaiting delivery</span></div><div class="tx"><strong>P91K · $75</strong><span>Done</span><span class="status">Completed</span></div></div></section>${nav()}`; }
function createLink(){ return `<section class="page">${topbar('Create protected link')}<h1>Create link</h1><p class="meta">One transaction. Minimal details.</p><div class="stack section"><div class="field"><label for="amount">Amount</label><input id="amount" inputmode="decimal" value="50.00"></div><div class="field"><label for="category">Purchase type</label><select id="category"><option>Custom digital content</option><option>Digital commission</option><option>Pre-made digital content</option><option>Digital service</option></select></div><div class="field"><label for="deadline">Deliver by</label><select id="deadline"><option>Within 24 hours</option><option selected>Within 48 hours</option><option>Within 7 days</option></select></div><div class="field"><label for="alias">Delivery reference (optional)</label><input id="alias" placeholder="Reddit / Discord reference"></div><button class="primary" onclick="created()">Create link</button></div></section>${nav()}`; }
function created(){ app.innerHTML = `<section class="page">${topbar('Ready to share')}<div class="success-mark">✓</div><div class="center"><h1>Link ready</h1><p class="meta">$50 · delivery within 48 hours</p></div><div class="section"><div class="linkbox">paid.example/maya/4J7-R9Q-X2</div></div><div class="stack section"><button class="primary" onclick="navigator.clipboard?.writeText('https://paid.example/maya/4J7-R9Q-X2')">Copy link</button><button class="secondary" onclick="tab('home')">Done</button></div></section>${nav()}`; }
function transactions(){ return `<section class="page">${topbar('Transactions')}<h1>Activity</h1><div class="section"><div class="tx"><strong>A82F · $50</strong><span>Today</span><span class="status">Awaiting delivery · Anonymous Buyer</span></div><div class="tx"><strong>P91K · $75</strong><span>Yesterday</span><span class="status">Completed · Verified Buyer</span></div><div class="tx"><strong>M44D · $40</strong><span>Aug 26</span><span class="status">Delivered · awaiting buyer</span></div><div class="tx"><strong>K20P · $100</strong><span>Aug 24</span><span class="status">Completed</span></div></div></section>${nav()}`; }
function trust(){ return `<section class="page">${topbar('Public reputation')}<div class="center"><div class="kicker">${creator.name} ✓</div><h1>${creator.tier}</h1><div class="amount" style="font-size:38px">${creator.rating} ★</div><div class="meta">${creator.completed} completed transactions</div></div><hr class="divider"><div class="stack"><div class="row"><span>Identity</span><strong>Verified ✓</strong></div><div class="row"><span>Member since</span><strong>Aug 2026</strong></div><div class="row"><span>Public buyer identities</span><strong>Private</strong></div></div><div class="section notice">Trust is earned from eligible transactions. It cannot be purchased. Faster payout eligibility also considers private payment risk and account security.</div></section>${nav()}`; }
function account(){ return `<section class="page">${topbar('Account')}<h1>${creator.name}</h1><div class="section stack"><button class="secondary">Security & passkeys</button><button class="secondary">Payout destination</button><button class="secondary">Privacy</button><button class="secondary">Support</button><button class="secondary">Legal & policies</button></div><div class="section notice">Changing a payout destination triggers additional verification and temporarily pauses accelerated payout eligibility.</div></section>${nav()}`; }

function buyer(){ return `<section class="page">${topbar('Protected transaction')}<div class="row"><div><div class="kicker">${creator.name} ✓</div><h2>${creator.tier}</h2><div class="meta">${creator.rating} ★ · ${creator.completed} completed</div></div><span class="badge">VERIFIED</span></div><div class="section price-box"><div class="amount">$50.00</div><div>Protected digital purchase</div><div class="meta">Delivery within 48 hours</div></div><div class="protection"><span class="check">✓</span>Protected under the transaction protection policy if the agreed deliverable is not provided.</div><div class="notice">Private by default: the creator sees “Anonymous Buyer,” not your cardholder identity.</div><div class="stack section"><button class="primary" onclick="mockPay()">Continue to pay</button><button class="secondary" onclick="setMode('creator')">View creator demo</button></div><hr class="divider"><p class="meta">Payment would be handled by an approved specialist payment provider. This prototype does not collect payment details.</p></section>`; }
function mockPay(){ app.innerHTML = `<section class="page">${topbar('Payment simulation')}<div class="success-mark">✓</div><div class="center"><h1>Paid</h1><p class="meta">Order A82F</p></div><div class="section notice">Your identity is hidden from the creator. This is a simulated transaction; no payment was processed.</div><div class="stack section"><button class="primary" onclick="receipt()">View transaction</button><button class="secondary">Create account (optional)</button></div></section>`; }
function receipt(){ app.innerHTML = `<section class="page">${topbar('Order A82F')}<div class="row"><div><div class="kicker">${creator.name} ✓</div><h2>$50.00</h2></div><span class="badge">PAID</span></div><hr class="divider"><div class="stack"><div class="row"><span>Status</span><strong>Awaiting delivery</strong></div><div class="row"><span>Deliver by</span><strong>48 hours</strong></div><div class="row"><span>Your identity</span><strong>Anonymous</strong></div></div><div class="stack section"><button class="primary">Confirm received</button><button class="secondary">Report a problem</button></div><p class="meta section">Access to a real guest transaction would use a private high-entropy credential separate from this public order code.</p></section>`; }

function render(){ if(mode==='buyer') { app.innerHTML=buyer(); return; } const screens={home:creatorHome,create:createLink,transactions,trust,account}; app.innerHTML=screens[creatorTab](); }
render();

if ('serviceWorker' in navigator && location.protocol !== 'file:') {
  window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
}
